"""initial schema

Revision ID: c09b0f92d00d
Revises: 
Create Date: 2026-04-06 00:33:27.264739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c09b0f92d00d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_article_id', sa.String(length=200), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('publisher', sa.String(length=255), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_articles_published_at', 'articles', ['published_at'], unique=False)
    op.create_index('ux_articles_source_article_id', 'articles', ['source_type', 'source_article_id'], unique=True, postgresql_where=sa.text('source_article_id IS NOT NULL'))
    op.create_index('ux_articles_url', 'articles', ['url'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('default_language', sa.String(length=10), server_default='ko', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ux_users_email_lower', 'users', [sa.literal_column('lower(email)')], unique=True)
    op.create_table('crawl_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('force_run', sa.Boolean(), nullable=False),
    sa.Column('article_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawl_runs_id'), 'crawl_runs', ['id'], unique=False)
    op.create_table('credit_wallets',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('balance', sa.Integer(), server_default='0', nullable=False),
    sa.CheckConstraint('balance >= 0', name='chk_credit_wallet_balance_nonnegative'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('feedbacks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('article_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('label', sa.String(length=10), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("label IN ('LIKE', 'DISLIKE')", name='chk_feedback_label'),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_feedbacks_article_user', 'feedbacks', ['article_id', 'user_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='QUEUED', nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("job_type IN ('REPORT_EMAIL', 'SUMMARY_EMAIL', 'CRAWL', 'OTHER')", name='chk_jobs_job_type'),
    sa.CheckConstraint("status IN ('QUEUED', 'RUNNING', 'SUCCESS', 'FAIL', 'CANCELLED')", name='chk_jobs_status'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_jobs_status_scheduled_for', 'jobs', ['status', 'scheduled_for'], unique=False)
    op.create_index('ix_jobs_user_created_at', 'jobs', ['user_id', 'created_at'], unique=False)
    op.create_table('keywords',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('keyword_text', sa.String(length=255), nullable=False),
    sa.Column('language', sa.String(length=10), server_default='ko', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'keyword_text', name='uq_keywords_user_keyword_text')
    )
    op.create_index('ix_keywords_user_active', 'keywords', ['user_id', 'is_active'], unique=False)
    op.create_index('ux_keywords_user_keyword_lower', 'keywords', ['user_id', sa.literal_column('lower(keyword_text)')], unique=True)
    op.create_table('reports',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('report_type', sa.String(length=20), server_default='MONTHLY', nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('content_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("report_type IN ('MONTHLY', 'WEEKLY', 'DAILY', 'CUSTOM')", name='chk_reports_report_type'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'report_type', 'period_start', 'period_end', name='uq_reports_user_type_period')
    )
    op.create_index('ix_reports_period', 'reports', ['report_type', 'period_start', 'period_end'], unique=False)
    op.create_index('ix_reports_user_created_at', 'reports', ['user_id', 'created_at'], unique=False)
    op.create_table('summaries',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('article_id', sa.BigInteger(), nullable=False),
    sa.Column('language', sa.String(length=10), server_default='ko', nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('model_name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_summaries_article_language', 'summaries', ['article_id', 'language', 'created_at'], unique=False)
    op.create_table('translations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('article_id', sa.BigInteger(), nullable=False),
    sa.Column('source_lang', sa.String(length=10), nullable=False),
    sa.Column('target_lang', sa.String(length=10), nullable=False),
    sa.Column('translated_text', sa.Text(), nullable=False),
    sa.Column('engine_name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id', 'source_lang', 'target_lang', 'engine_name', name='uq_translations_article_lang_engine')
    )
    op.create_table('user_tokens',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_type', sa.String(length=30), server_default='Bearer', nullable=False),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider', name='uq_user_tokens_user_provider')
    )
    op.create_index('ix_user_tokens_expires_at', 'user_tokens', ['expires_at'], unique=False)
    op.create_index('ix_user_tokens_provider', 'user_tokens', ['provider'], unique=False)
    op.create_index('ix_user_tokens_user_active', 'user_tokens', ['user_id', 'is_active'], unique=False)
    op.create_table('article_matches',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('article_id', sa.BigInteger(), nullable=False),
    sa.Column('keyword_id', sa.BigInteger(), nullable=False),
    sa.Column('crawl_run_id', sa.BigInteger(), nullable=True),
    sa.Column('matched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['crawl_run_id'], ['crawl_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id', 'keyword_id', name='uq_article_matches_article_keyword')
    )
    op.create_index('ix_article_matches_article', 'article_matches', ['article_id'], unique=False)
    op.create_index('ix_article_matches_keyword', 'article_matches', ['keyword_id'], unique=False)
    op.create_table('crawl_run_keywords',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('crawl_run_id', sa.BigInteger(), nullable=False),
    sa.Column('keyword_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['crawl_run_id'], ['crawl_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('crawl_run_id', 'keyword_id', name='uq_crawl_run_keywords_run_keyword')
    )
    op.create_table('credit_transactions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('tx_type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('related_job_id', sa.BigInteger(), nullable=True),
    sa.Column('external_ref', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            (tx_type IN ('CHARGE', 'REFUND') AND amount > 0)\n            OR (tx_type = 'SPEND' AND amount < 0)\n            OR (tx_type = 'ADJUST' AND amount <> 0)\n            ", name='chk_credit_transactions_amount_sign'),
    sa.CheckConstraint("tx_type IN ('CHARGE', 'SPEND', 'REFUND', 'ADJUST')", name='chk_credit_transactions_tx_type'),
    sa.CheckConstraint('amount <> 0', name='chk_credit_transactions_amount_nonzero'),
    sa.ForeignKeyConstraint(['related_job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_credit_tx_job', 'credit_transactions', ['related_job_id'], unique=False)
    op.create_index('ix_credit_tx_user_created_at', 'credit_transactions', ['user_id', 'created_at'], unique=False)
    op.create_index('ux_credit_tx_external_ref', 'credit_transactions', ['external_ref'], unique=True, postgresql_where=sa.text('external_ref IS NOT NULL'))
    op.create_table('email_deliveries',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('job_id', sa.BigInteger(), nullable=True),
    sa.Column('to_email', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='QUEUED', nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('QUEUED', 'SENT', 'FAIL')", name='chk_email_deliveries_status'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_email_job', 'email_deliveries', ['job_id'], unique=False)
    op.create_index('ix_email_status_sent_at', 'email_deliveries', ['status', 'sent_at'], unique=False)
    op.create_index('ix_email_user_created_at', 'email_deliveries', ['user_id', 'created_at'], unique=False)
    op.create_table('importance_scores',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('article_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='COMPLETED', nullable=False),
    sa.Column('scored_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('engine', sa.String(length=100), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('is_current', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('trigger_feedback_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trigger_feedback_id'], ['feedbacks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_importance_scores_user_current', 'importance_scores', ['user_id', 'is_current', 'created_at'], unique=False)
    op.create_index('ux_importance_current', 'importance_scores', ['article_id', 'user_id'], unique=True, postgresql_where=sa.text('is_current IS true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ux_importance_current', table_name='importance_scores', postgresql_where=sa.text('is_current IS true'))
    op.drop_index('ix_importance_scores_user_current', table_name='importance_scores')
    op.drop_table('importance_scores')
    op.drop_index('ix_email_user_created_at', table_name='email_deliveries')
    op.drop_index('ix_email_status_sent_at', table_name='email_deliveries')
    op.drop_index('ix_email_job', table_name='email_deliveries')
    op.drop_table('email_deliveries')
    op.drop_index('ux_credit_tx_external_ref', table_name='credit_transactions', postgresql_where=sa.text('external_ref IS NOT NULL'))
    op.drop_index('ix_credit_tx_user_created_at', table_name='credit_transactions')
    op.drop_index('ix_credit_tx_job', table_name='credit_transactions')
    op.drop_table('credit_transactions')
    op.drop_table('crawl_run_keywords')
    op.drop_index('ix_article_matches_keyword', table_name='article_matches')
    op.drop_index('ix_article_matches_article', table_name='article_matches')
    op.drop_table('article_matches')
    op.drop_index('ix_user_tokens_user_active', table_name='user_tokens')
    op.drop_index('ix_user_tokens_provider', table_name='user_tokens')
    op.drop_index('ix_user_tokens_expires_at', table_name='user_tokens')
    op.drop_table('user_tokens')
    op.drop_table('translations')
    op.drop_index('ix_summaries_article_language', table_name='summaries')
    op.drop_table('summaries')
    op.drop_index('ix_reports_user_created_at', table_name='reports')
    op.drop_index('ix_reports_period', table_name='reports')
    op.drop_table('reports')
    op.drop_index('ux_keywords_user_keyword_lower', table_name='keywords')
    op.drop_index('ix_keywords_user_active', table_name='keywords')
    op.drop_table('keywords')
    op.drop_index('ix_jobs_user_created_at', table_name='jobs')
    op.drop_index('ix_jobs_status_scheduled_for', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index('ix_feedbacks_article_user', table_name='feedbacks')
    op.drop_table('feedbacks')
    op.drop_table('credit_wallets')
    op.drop_index(op.f('ix_crawl_runs_id'), table_name='crawl_runs')
    op.drop_table('crawl_runs')
    op.drop_index('ux_users_email_lower', table_name='users')
    op.drop_table('users')
    op.drop_index('ux_articles_url', table_name='articles')
    op.drop_index('ux_articles_source_article_id', table_name='articles', postgresql_where=sa.text('source_article_id IS NOT NULL'))
    op.drop_index('ix_articles_published_at', table_name='articles')
    op.drop_table('articles')
    # ### end Alembic commands ###
